name: NASA Project CI   # Name of this workflow (what it’s called)

# When should this workflow run?
on:
  push:
    branches: [ master ]   # Run this workflow when you push code to master branch
  pull_request:
    branches: [ master ]   # Run this workflow when someone asks to add code to master (PR)

jobs:
  build:   # Job is like a big task. This one is called "build"
    env:   # Environment variables (special info your code can use)
      CI: true   # Tells the code "we are in CI mode"
      MONGO_URL: mongodb://localhost/nasa   # Link to MongoDB database for tests

    strategy:   # Test on different versions of Node and MongoDB
      matrix:
        node-version: [20.x, 22.x]   # Test on Node version 20 and 22
        mongodb-version: ['7.0']     # Test on MongoDB version 7.0

    runs-on: ubuntu-latest   # Uses a Linux computer to run this job. could be any/all operating systems

    steps:   # Steps are like instructions. They run one by one
      - uses: actions/checkout@v4   # Step 1: get the code from GitHub

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4   # Step 2: set up Node.js
        with:
          node-version: ${{ matrix.node-version }}   # Pick Node version from matrix

      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.11.0   # Step 3: set up MongoDB
        with:
          mongodb-version: ${{ matrix.mongodb-version }}   # Pick MongoDB version from matrix

      - run: npm install   # Step 4: install all libraries the project needs

      - run: npm run build --prefix client   # Step 5: build the front-end client (turn code into something that runs)

      - run: npm test   # Step 6: run all tests to make sure nothing is broken
